=== viragtripathi/workspace/be/SkyTeamBES/SharedResources/Schemas/FlightSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.schemas.skyteam.com/2016/09/enterprise/Flight" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fl="http://www.schemas.skyteam.com/2016/09/enterprise/Flight">

	<xsd:complexType name="BagsNotLoadedType">
		<xsd:sequence>
			<xsd:element name="BagTagID" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="FlightType">
		<xsd:annotation>
			<xsd:documentation>Flight Events Details</xsd:documentation>
		</xsd:annotation>		
		<xsd:sequence>
			<xsd:element name="EventType" type="xsd:string" />
			<xsd:element name="FlightKey" type="xsd:string" />
			<xsd:element name="FlightSegmentNumber" type="xsd:string" />
			<xsd:element name="AirlineCode" type="xsd:string" />
			<xsd:element name="FlightNumber" type="xsd:string" />
			<xsd:element name="FlightDate" type="xsd:dateTime" />
			<xsd:element name="OriginStnCode" type="xsd:string" />
			<xsd:element name="DestStnCode" type="xsd:string" />			
			<xsd:element name="SegmentStatus" type="xsd:string" />
			<xsd:element name="InternationalDomesticFlag" type="xsd:boolean" />
			<xsd:element name="EquipmentType" type="xsd:string" />
			<xsd:element name="ScheduledDepartureTime" type="xsd:dateTime" />
			<xsd:element name="ScheduledArrivalTime" type="xsd:dateTime" />
			<xsd:element name="EstimatedDepartureTime" type="xsd:dateTime" />
			<xsd:element name="EstimatedArrivalTime" type="xsd:dateTime" />
			<xsd:element name="DepartureGate" type="xsd:string" />
			<xsd:element name="ArrivalGate" type="xsd:string" />
			<xsd:element name="TotalBagsCheckedIn" type="xsd:integer" />
			<xsd:element name="TotalBagsLoaded" type="xsd:integer" />
			<xsd:element name="TotalBagsRerouted" type="xsd:integer" />
			<xsd:element name="TotalBagsDelivered" type="xsd:integer" />
			<xsd:element name="BagsNotLoaded" type="fl:BagsNotLoadedType" minOccurs="0"/>
		</xsd:sequence>

	</xsd:complexType>
	

	<xsd:element name="Flight" type="fl:FlightType"></xsd:element>
</xsd:schema>

=== viragtripathi/workspace/be/SkyTeamBES/TestData/Flight/SCHEDULED_EventType.xml
<?xml version="1.0" encoding="UTF-8"?>
<fl:Flight xmlns:fl="http://www.schemas.skyteam.com/2016/09/enterprise/Flight" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.schemas.skyteam.com/2016/09/enterprise/Flight FlightSchema.xsd ">
  <fl:EventType>SCHEDULED</fl:EventType>
  <fl:FlightKey>DL0001ATLDXB20160916</fl:FlightKey>
  <fl:FlightSegmentNumber>1</fl:FlightSegmentNumber>
  <fl:AirlineCode>DL</fl:AirlineCode>
  <fl:FlightNumber>0001</fl:FlightNumber>
  <fl:FlightDate>2001-12-31T12:00:00</fl:FlightDate>
  <fl:OriginStnCode>ATL</fl:OriginStnCode>
  <fl:DestStnCode>DXB</fl:DestStnCode>
  <fl:SegmentStatus>Scheduled</fl:SegmentStatus>
  <fl:InternationalDomesticFlag>true</fl:InternationalDomesticFlag>
  <fl:EquipmentType>777</fl:EquipmentType>
  <fl:ScheduledDepartureTime>2001-12-31T12:00:00</fl:ScheduledDepartureTime>
  <fl:ScheduledArrivalTime>2001-12-31T12:00:00</fl:ScheduledArrivalTime>
  <fl:EstimatedDepartureTime>2001-12-31T12:00:00</fl:EstimatedDepartureTime>
  <fl:EstimatedArrivalTime>2001-12-31T12:00:00</fl:EstimatedArrivalTime>
  <fl:DepartureGate>E16</fl:DepartureGate>
  <fl:ArrivalGate>D12</fl:ArrivalGate>
</fl:Flight>
