=== viragtripathi/workspace/be/SkyTeamBES/SharedResources/Schemas/PassengerSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.schemas.skyteam.com/2016/09/enterprise/Passenger" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:pnr="http://www.schemas.skyteam.com/2016/09/enterprise/Passenger">

	<xsd:complexType name="PassengerType">
		<xsd:annotation>
			<xsd:documentation>Passenger Events Details</xsd:documentation>
		</xsd:annotation>		
		<xsd:sequence>
			<xsd:element name="EventType" type="xsd:string" />
			<xsd:element name="FlightKey" type="xsd:string" />
			<xsd:element name="AirlineCode" type="xsd:string" />
			<xsd:element name="FlightSegments" type="xsd:string" >
				<xsd:annotation>
					<xsd:documentation>An array of Flights (with leg info)</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="BagTags" type="xsd:string" >
				<xsd:annotation>
					<xsd:documentation>An Array of BagTag information</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="FlightNumber" type="xsd:string" />
			<xsd:element name="RecordLocator" type="xsd:string" />
			<xsd:element name="CutomerId" type="xsd:string" />
			<xsd:element name="BookingId" type="xsd:string" />
			<xsd:element name="FirstName" type="xsd:string" />
			<xsd:element name="LastName" type="xsd:string" />
			<xsd:element name="SeatNo" type="xsd:string" />
			<xsd:element name="FrequentFlyerStaus" type="xsd:string" />
			<xsd:element name="OriginLocalDate" type="xsd:dateTime" />
			<xsd:element name="OriginStnCode" type="xsd:string" />
			<xsd:element name="DestStnCode" type="xsd:string" />
		</xsd:sequence>

	</xsd:complexType>
	

	<xsd:element name="Passenger" type="pnr:PassengerType"></xsd:element>
</xsd:schema>

=== viragtripathi/workspace/be/SkyTeamBES/TestData/Passenger/PassengerCheckedIn.xml
<?xml version="1.0" encoding="UTF-8"?>
<pnr:Passenger xmlns:pnr="http://www.schemas.skyteam.com/2016/09/enterprise/Passenger" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.schemas.skyteam.com/2016/09/enterprise/Passenger ../SharedResources/Schemas/PassengerSchema.xsd ">
  <pnr:EventType>CHECKED_IN</pnr:EventType>
  <pnr:FlightKey>pnr:FlightKey</pnr:FlightKey>
  <pnr:AirlineCode>DL</pnr:AirlineCode>
  <pnr:FlightSegments>1</pnr:FlightSegments>
  <pnr:BagTags>168616</pnr:BagTags>
  <pnr:FlightNumber>0001</pnr:FlightNumber>
  <pnr:RecordLocator>ZTJE26</pnr:RecordLocator>
  <pnr:CutomerId>123</pnr:CutomerId>
  <pnr:BookingId>456</pnr:BookingId>
  <pnr:FirstName>Tim</pnr:FirstName>
  <pnr:LastName>Cook</pnr:LastName>
  <pnr:SeatNo>6A</pnr:SeatNo>
  <pnr:FrequentFlyerStaus>GM</pnr:FrequentFlyerStaus>
  <pnr:OriginLocalDate>2001-12-31T12:00:00</pnr:OriginLocalDate>
  <pnr:OriginStnCode>ATL</pnr:OriginStnCode>
  <pnr:DestStnCode>DXB</pnr:DestStnCode>
</pnr:Passenger>
